<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PES.Core\PES.Core.csproj" />
    <ProjectReference Include="..\PES.Domain\PES.Domain.csproj" />
    <ProjectReference Include="..\PES.Application\PES.Application.csproj" />
    <ProjectReference Include="..\PES.Infrastructure\PES.Infrastructure.csproj" />
    <ProjectReference Include="..\PES.Messaging\PES.Messaging.csproj" />
    <ProjectReference Include="..\PES.Security\PES.Security.csproj" />
    <ProjectReference Include="..\PES.Observability\PES.Observability.csproj" />
  </ItemGroup>

</Project>
